apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: dev
  labels:
    app: spring-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-pod
  template:
    metadata:
      labels:
        app: spring-pod
    spec:
      containers:
        - name: java-app
          image: nginx:latest
          ports:
            - containerPort: 8080

